Proyecto01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWeb.urls')),
    path('articulos/', include('articulos.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carrito/', include('carrito.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include ('pedidos.urls'))
]

carrito/urls.py
from django.urls import path
from . import views

app_name = "carrito"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name = "agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name = "eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto, name = "restar"),
    path('limpiar/', views.limpiar_carrito, name = "agregar"),
]

tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="Tienda"),
]

carrito/models.py
from django.db import models

# Create your models here.

tienda/models.py
from django.db import models

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null = True, blank = True)
    precio = models.IntegerField()
    disponibilidad = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

carrito/views.py
from django.shortcuts import render
from .carrito import Carrito
from tienda.models import Producto
from django.shortcuts import redirect

def agregar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id = producto_id)
    carrito.agregar(producto = producto)
    return redirect ("Tienda")

def eliminar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id = producto_id)
    carrito.eliminar(producto = producto)
    return redirect ("Tienda")

def restar_producto(request, producto_id):
    carrito = Carrito(request)
    producto = Producto.objects.get(id = producto_id)
    carrito.restar_producto(producto = producto)
    return redirect ("Tienda")

def limpiar_carrito(request, producto_id):
    carrito = Carrito(request)
    carrito.limpiar_carrito()
    return redirect ("Tienda")

tienda/views.py
from django.shortcuts import render
from .models import Producto

def tienda(request):
    productos = Producto.objects.all()
    return render(request, "tienda/tienda.html", {"productos": productos})

tienda/templates/carrito/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>

        <tr>
            <th colspan="3" class="text-center">
                Carrito compras
            </th>
        </tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
    </thead>
    <tbody>
        {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
                <tr class="text-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carrito:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carrito:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                        ${{value.precio}}
                    </td> 
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class = "alert alert-danger text-center">
                        Sin Productos
                    </div> 
                </td>
            </tr>
        {% endif %}
    </tbody>
<tfoot>
    <tr>
        <td colspan="3">
            Total: ${{importe_total_carrito}}
        </td>
    </tr>
    {% if request.session.carrito.items %}
    <tr>
        <td colspan="3" style="text-align: center;">

            <a hred="#" class="btn btn-success">Hacer pedido</a>


        </td>
    </tr>
    {% endif %}
</tfoot>

</table>